sudo: false
language: perl
matrix:
    fast_finish: true
perl:
    - "5.24"
    - "5.14"
install:
    - cpanm --quiet --notest --skip-satisfied Dist::Zilla Dist::Zilla::App::Command::cover App::cpm
    - cpm install -w 2 --mirror=http://cpan.cpantesters.org/ -g $(dzil authordeps --missing)
    - cpm install -w 2 --mirror=http://cpan.cpantesters.org/ -g $(dzil listdeps --author --missing)

script:
    - dzil smoke --release --author && dzil xtest && dzil cover -test
