---
abstract: 'represents a financial stock exchange object.'
author:
  - 'DERIV <DERIV@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::Deep: '0'
  Test::Exception: '0'
  Test::FailWarnings: '0.008'
  Test::More: '0.98'
  Test::Most: '0.34'
  perl: '5.006'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '7.64'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.029, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Finance-Exchange
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  Finance::Exchange:
    file: lib/Finance/Exchange.pm
    version: '0.02'
requires:
  Clone: '0'
  File::ShareDir: '0'
  Moose: '0'
  Time::Duration::Concise::Localize: '0'
  YAML::XS: '0'
resources:
  bugtracker: https://github.com/binary-com/perl-Finance-Exchange/issues
  homepage: https://github.com/binary-com/perl-Finance-Exchange
  repository: https://github.com/binary-com/perl-Finance-Exchange.git
version: '0.02'
x_authority: cpan:DERIV
x_contributors:
  - 'Jun Bon <junbon@binary.com>'
  - 'Md Masud Rana <masud@regentmarkets.com>'
  - 'Jean-Yves Sireau <jy@binary.com>'
  - 'Tom Molesworth <tom@binary.com>'
  - 'Yng Shan <yngshan@binary.com>'
  - 'chylli-binary <52912308+chylli-binary@users.noreply.github.com>'
  - 'lim-deriv <lim.kai@deriv.com>'
  - 'Arun Venkataraman <arun@regentmarkets.com>'
  - 'Hossein Shahsahebi <67314444+hossein-binary@users.noreply.github.com>'
  - 'mukesh-deriv <85932084+mukesh-deriv@users.noreply.github.com>'
  - 'Raunak Kathuria <raunakkathuria@gmail.com>'
  - 'stanly-binary <stanly@binary.com>'
x_generated_by_perl: v5.26.2
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
